# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: project-stack-dyn
#   namespace: argo-cd
# spec:
#   generators:
#     - scmProvider:
#         cloneProtocol: git
#         filters:
#           - branchMatch: ^issue/.*
#             repositoryMatch: manifests
#         gitlab:
#           group: "12345678" 
#           allBranches: true
#           includeSubgroups: true
#           tokenRef:
#             secretName: gitlab-token
#             key: token
#   template:
#     metadata:
#       name: "{{branchNormalized}}"
#     spec:
#       source:
#         path: helm/
#         repoURL: https://github.com/VitalyEst/applicationSet-test.git
#         targetRevision: "{{branch}}"
#         helm:
#           values: |
#             fullnameOverride: "{{branchNormalized}}"
#             ingress:
#               enabled: true
#               annotations: {}
#               hosts:
#                 - host: {{branchNormalized}}.dyn.project.ru
#                   paths:
#                     - path: /
#                       pathType: ImplementationSpecific
#       project: project-dyn
#       destination:
#         namespace: 'argo-app-project-dyn'
#         server: https://kubernetes.default.svc
#       syncPolicy:
#         automated:
#           selfHeal: true
#           prune: true
#           allowEmpty: true
#         syncOptions:
#           - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set-branch
  namespace: argo-cd
spec:
  generators:
  - scmProvider:
      github:
        organization: VitalyEst-org
      cloneProtocol: https
      filters:
      - repositoryMatch: applicationSet-test
        branchMatch: ^issue/.*
  template:
    metadata:
      name: "{{branchNormalized}}"
    spec:
      project: "default"
      source:
        repoURL: https://github.com/VitalyEst-org/applicationSet-test.git
        targetRevision: '{{ branch }}'
        path: applicationSetBranch
        helm:
          values: |
            fullnameOverride: "{{branchNormalized}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: application-set-branch
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true